export const VOYAGE_CHAPTERS = [
  { id: 'calm-cove', number: 1, title: 'Calm Cove', description: 'Small crews and room to explore.' },
  { id: 'rolling-waters', number: 2, title: 'Rolling Waters', description: 'Races, escorts, and moving walls.' },
  { id: 'open-sea', number: 3, title: 'Open Sea', description: 'Block channels and break through.' },
  { id: 'storm-waters', number: 4, title: 'Storm Waters', description: 'Protectors, swarms, and counterattacks.' },
  { id: 'legendary-voyages', number: 5, title: 'Legendary Voyages', description: 'The hardest voyages.' },
]

// Every voyage is a complete, replayable two-player position. Instance suffixes
// allow several travelers of the same kind while keeping one shared movement rule.
export const VOYAGES = [
  {
    id: 'great-whale-chase', order: 1, chapterId: 'calm-cove', title: 'The Great Whale Chase',
    strapline: 'Two boats chase one whale.',
    story: 'Close the channels before the tide clock runs out.',
    objective: 'Boats: surround the whale. Whale: keep a safe channel open.',
    lesson: 'Chase and escape', pieceCount: 3, difficulty: 1, available: true,
    vessel: 'cutter', goal: 'corner', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxWhaleTurns: 18, maxMoves: 35, turn: 'boats',
    pieces: { tug: { row: 6, col: 1 }, cutter: { row: 6, col: 5 }, whale: { row: 1, col: 3 } },
  },
  {
    id: 'lighthouse-hunt', order: 2, chapterId: 'calm-cove', title: 'The Lighthouse Hunt',
    strapline: 'The dredger controls straight channels.',
    story: 'Use the tug and dredger together. The whale looks for gaps.',
    objective: 'Boats: surround the whale. Whale: keep a safe route open until the tide clock.',
    lesson: 'Straight-channel chase', pieceCount: 3, difficulty: 1, available: true,
    vessel: 'dredger', goal: 'corner', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxWhaleTurns: 18, maxMoves: 35, turn: 'boats',
    pieces: { tug: { row: 6, col: 2 }, dredger: { row: 5, col: 4 }, whale: { row: 1, col: 6 } },
  },
  {
    id: 'bring-dinghy-home', order: 3, chapterId: 'calm-cove', title: 'Bring the Dinghy Home',
    strapline: 'Guide one dinghy to the far shore.',
    story: 'Reach the far shore, grow a cutter, and finish the chase.',
    objective: 'Boats: grow a cutter, then surround the whale. Whale: stop it and last until the tide clock.',
    lesson: 'Escort and blockade', pieceCount: 3, difficulty: 1, available: true,
    vessel: 'dinghy', goal: 'boats-escort', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 50, turn: 'boats',
    pieces: { tug: { row: 7, col: 0 }, dinghy: { row: 5, col: 3 }, whale: { row: 2, col: 5 } },
  },
  {
    id: 'twin-dredger-sweep', order: 4, chapterId: 'rolling-waters', title: 'Twin Dredger Sweep',
    strapline: 'Two dredgers form a moving wall.',
    story: 'Keep the wall together. The whale looks for a gap.',
    objective: 'Boats: surround the whale with the dredgers. Whale: break through and keep swimming.',
    lesson: 'Moving barriers', pieceCount: 4, difficulty: 1, available: true,
    vessel: 'dredger', goal: 'corner', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 35, turn: 'boats',
    pieces: { tug: { row: 7, col: 3 }, dredger: { row: 6, col: 1 }, dredger2: { row: 6, col: 6 }, whale: { row: 1, col: 4 } },
  },
  {
    id: 'two-dinghies-home', order: 5, chapterId: 'rolling-waters', title: 'Two Dinghies Home',
    strapline: 'Two dinghies need safe routes.',
    story: 'Protect both dinghies or use one as a decoy.',
    objective: 'Boats: grow a cutter, then surround the whale. Whale: stop both and last until the tide clock.',
    lesson: 'Choices and decoys', pieceCount: 4, difficulty: 2, available: true,
    vessel: 'dinghy', goal: 'boats-escort', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 56, turn: 'boats',
    pieces: { tug: { row: 7, col: 3 }, dinghy: { row: 5, col: 2 }, dinghy2: { row: 5, col: 5 }, whale: { row: 1, col: 4 } },
  },
  {
    id: 'runaway-dinghy', order: 6, chapterId: 'rolling-waters', title: 'The Runaway Silver Fish',
    strapline: 'A dredger races a silver fish.',
    story: 'The fish runs for shore. The dredger must cut it off.',
    objective: 'Boats: stop the fish, then surround the whale. Sea life: grow an orca, then surround the tug.',
    lesson: 'Interception race', pieceCount: 4, difficulty: 2, available: true,
    vessel: 'dredger', goal: 'animals-escape', gameBalance: 'chase', clockWinner: 'boats', noProgressWinner: null, maxMoves: 52, turn: 'animals',
    pieces: { tug: { row: 7, col: 5 }, dredger: { row: 5, col: 3 }, whale: { row: 0, col: 1 }, fish: { row: 2, col: 4 } },
  },
  {
    id: 'silver-shoal-sprint', order: 7, chapterId: 'rolling-waters', title: 'Silver Shoal Sprint',
    strapline: 'Both crews race for shore.',
    story: 'Advance, block, or capture. Reaching shore adds a strong helper.',
    objective: 'Either crew: grow a helper, then surround the other crew’s leader.',
    lesson: 'Race and block', pieceCount: 6, difficulty: 2, available: true,
    vessel: 'dinghy', goal: 'race', gameBalance: 'even', clockWinner: null, noProgressWinner: null, maxMoves: 48, turn: 'boats',
    pieces: { tug: { row: 7, col: 0 }, dinghy: { row: 6, col: 2 }, dinghy2: { row: 6, col: 5 }, whale: { row: 0, col: 7 }, fish: { row: 1, col: 2 }, fish2: { row: 1, col: 5 } },
  },
  {
    id: 'lantern-passage', order: 8, chapterId: 'open-sea', title: 'Lantern Passage',
    strapline: 'The sloop controls diagonal channels.',
    story: 'The silver fish looks for a path the sloop cannot cover.',
    objective: 'Boats: stop the fish, then surround the whale. Sea life: grow an orca, then surround the tug.',
    lesson: 'Diagonal channels', pieceCount: 4, difficulty: 2, available: true,
    vessel: 'sloop', goal: 'animals-escape', gameBalance: 'chase', clockWinner: 'boats', noProgressWinner: null, maxMoves: 54, turn: 'animals',
    pieces: { tug: { row: 7, col: 6 }, sloop: { row: 4, col: 3 }, whale: { row: 0, col: 1 }, fish: { row: 2, col: 5 } },
  },
  {
    id: 'reef-shark-raid', order: 9, chapterId: 'open-sea', title: 'Reef Shark Raid',
    strapline: 'One shark faces three dinghies.',
    story: 'Spread out. The shark guards the straight channels.',
    objective: 'Boats: grow a cutter, then surround the whale. Sea life: stop the dinghies and surround the tug.',
    lesson: 'Hunter and swarm', pieceCount: 6, difficulty: 2, available: true,
    vessel: 'dinghy', goal: 'boats-escort', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 62, turn: 'boats',
    pieces: { tug: { row: 7, col: 7 }, dinghy: { row: 6, col: 1 }, dinghy2: { row: 6, col: 3 }, dinghy3: { row: 6, col: 5 }, whale: { row: 0, col: 0 }, shark: { row: 3, col: 4 } },
  },
  {
    id: 'dolphin-patrol', order: 10, chapterId: 'open-sea', title: 'Dolphin Patrol',
    strapline: 'A dolphin guards unusual routes.',
    story: 'Two dinghies must slip past its landing spots.',
    objective: 'Boats: grow a cutter, then surround the whale. Sea life: stop both dinghies and surround the tug.',
    lesson: 'Leaps and escape lanes', pieceCount: 5, difficulty: 3, available: true,
    vessel: 'dinghy', goal: 'boats-escort', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 60, turn: 'boats',
    pieces: { tug: { row: 7, col: 7 }, dinghy: { row: 6, col: 2 }, dinghy2: { row: 6, col: 5 }, whale: { row: 0, col: 0 }, dolphin: { row: 3, col: 3 } },
  },
  {
    id: 'great-harbor-race', order: 11, chapterId: 'open-sea', title: 'The Great Harbor Race',
    strapline: 'Race forward or stop the other crew.',
    story: 'Each turn: advance, protect, or intercept.',
    objective: 'Either crew: grow a helper, then surround the other crew’s leader.',
    lesson: 'Escort and counter-race', pieceCount: 8, difficulty: 3, available: true,
    vessel: 'dinghy', goal: 'race', gameBalance: 'even', clockWinner: null, noProgressWinner: null, maxMoves: 64, turn: 'boats',
    pieces: { tug: { row: 7, col: 7 }, dinghy: { row: 6, col: 1 }, dinghy2: { row: 6, col: 3 }, dinghy3: { row: 6, col: 5 }, whale: { row: 0, col: 0 }, fish: { row: 1, col: 2 }, fish2: { row: 1, col: 4 }, fish3: { row: 1, col: 6 } },
  },
  {
    id: 'cutter-and-shoal', order: 12, chapterId: 'open-sea', title: 'Cutter and the Silver Shoal',
    strapline: 'One cutter faces six silver fish.',
    story: 'The cutter hunts as the shoal races for shore.',
    objective: 'Boats: stop the shoal, then surround the whale. Sea life: grow an orca, then surround the tug.',
    lesson: 'Power against numbers', pieceCount: 9, difficulty: 3, available: true,
    vessel: 'cutter', goal: 'collect-animals', gameBalance: 'chase', clockWinner: 'boats', noProgressWinner: null, maxMoves: 72, turn: 'boats',
    pieces: { tug: { row: 7, col: 7 }, cutter: { row: 5, col: 6 }, whale: { row: 0, col: 0 }, fish: { row: 1, col: 1 }, fish2: { row: 1, col: 2 }, fish3: { row: 1, col: 3 }, fish4: { row: 2, col: 4 }, fish5: { row: 2, col: 5 }, fish6: { row: 2, col: 6 } },
  },
  {
    id: 'whale-and-dolphin', order: 13, chapterId: 'storm-waters', title: 'Whale and Dolphin',
    strapline: 'The whale has a dolphin helper.',
    story: 'The dolphin can break the boats’ net.',
    objective: 'Boats: surround the whale. Sea life: protect the whale and surround the tug.',
    lesson: 'Guarded escape', pieceCount: 4, difficulty: 3, available: true,
    vessel: 'cutter', goal: 'corner', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 76, turn: 'boats',
    pieces: { tug: { row: 7, col: 2 }, cutter: { row: 6, col: 5 }, whale: { row: 1, col: 4 }, dolphin: { row: 2, col: 2 } },
  },
  {
    id: 'twin-lantern-net', order: 14, chapterId: 'storm-waters', title: 'Twin Lantern Net',
    strapline: 'Two sloops cross diagonal channels.',
    story: 'Close the net together. The whale tries to split it.',
    objective: 'Boats: surround the whale with both lantern boats. Whale: break the net and keep moving.',
    lesson: 'Crossing diagonal nets', pieceCount: 4, difficulty: 4, available: true,
    vessel: 'sloop', goal: 'corner', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 82, turn: 'boats',
    pieces: { tug: { row: 7, col: 4 }, sloop: { row: 5, col: 2 }, sloop2: { row: 5, col: 5 }, whale: { row: 1, col: 4 } },
  },
  {
    id: 'last-silver-fish', order: 15, chapterId: 'storm-waters', title: 'The Last Silver Fish',
    strapline: 'One fish is close to shore.',
    story: 'The cutter has little time to stop it.',
    objective: 'Boats: stop the fish, then surround the whale. Sea life: grow an orca, then surround the tug.',
    lesson: 'Last-chance pursuit', pieceCount: 4, difficulty: 4, available: true,
    vessel: 'cutter', goal: 'animals-escape', gameBalance: 'chase', clockWinner: 'boats', noProgressWinner: null, maxMoves: 46, turn: 'animals',
    pieces: { tug: { row: 7, col: 1 }, cutter: { row: 5, col: 5 }, whale: { row: 0, col: 6 }, fish: { row: 5, col: 3 } },
  },
  {
    id: 'great-shoal-rebellion', order: 16, chapterId: 'storm-waters', title: 'The Great Dinghy Migration',
    strapline: 'Six dinghies face six dolphins.',
    story: 'Find one route through the leaping patrol.',
    objective: 'Boats: grow a cutter, then surround the whale. Sea life: stop the dinghies and surround the tug.',
    lesson: 'Large asymmetric battle', pieceCount: 14, difficulty: 4, available: true,
    vessel: 'dinghy', goal: 'boats-escort', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 90, turn: 'boats',
    pieces: { tug: { row: 7, col: 7 }, dinghy: { row: 6, col: 0 }, dinghy2: { row: 6, col: 1 }, dinghy3: { row: 6, col: 2 }, dinghy4: { row: 6, col: 3 }, dinghy5: { row: 6, col: 4 }, dinghy6: { row: 6, col: 5 }, whale: { row: 0, col: 0 }, dolphin: { row: 2, col: 0 }, dolphin2: { row: 2, col: 2 }, dolphin3: { row: 2, col: 4 }, dolphin4: { row: 3, col: 1 }, dolphin5: { row: 3, col: 3 }, dolphin6: { row: 3, col: 5 } },
  },
  {
    id: 'fog-bridge', order: 17, chapterId: 'legendary-voyages', title: 'Build the Fog Bridge',
    strapline: 'Shield a dinghy from a distant shark.',
    story: 'The sloop makes cover while the dinghy moves.',
    objective: 'Boats: grow a cutter, then surround the whale. Sea life: stop the dinghy and surround the tug.',
    lesson: 'Shelter and promotion', pieceCount: 5, difficulty: 4, available: true,
    vessel: 'sloop', goal: 'boats-escort', gameBalance: 'chase', clockWinner: 'whale', noProgressWinner: 'whale', maxMoves: 76, turn: 'boats',
    pieces: { tug: { row: 7, col: 6 }, sloop: { row: 5, col: 2 }, dinghy: { row: 4, col: 3 }, whale: { row: 0, col: 1 }, shark: { row: 2, col: 6 } },
  },
  {
    id: 'fog-line', order: 18, chapterId: 'legendary-voyages', title: 'Hold the Fog Line',
    strapline: 'Hold a line against two silver fish.',
    story: 'Wait, block the channel, then attack.',
    objective: 'Boats: stop both fish, then surround the whale. Sea life: grow an orca, then surround the tug.',
    lesson: 'Patient defense', pieceCount: 5, difficulty: 5, available: true,
    vessel: 'dredger', goal: 'animals-escape', gameBalance: 'chase', clockWinner: 'boats', noProgressWinner: null, maxMoves: 78, turn: 'animals',
    pieces: { tug: { row: 7, col: 6 }, dredger: { row: 5, col: 7 }, whale: { row: 0, col: 1 }, fish: { row: 4, col: 2 }, fish2: { row: 4, col: 3 } },
  },
  {
    id: 'cutter-against-dredger', order: 19, chapterId: 'legendary-voyages', title: 'Cutter Against Orca',
    strapline: 'A cutter and orca meet in open water.',
    story: 'Every attack can become a counterattack.',
    objective: 'Either crew: surround the other crew’s leader.',
    lesson: 'Counterattack duel', pieceCount: 4, difficulty: 5, available: true,
    vessel: 'cutter', goal: 'corner', gameBalance: 'even', clockWinner: null, noProgressWinner: null, maxMoves: 86, turn: 'boats',
    pieces: { tug: { row: 7, col: 1 }, cutter: { row: 5, col: 3 }, whale: { row: 0, col: 6 }, orca: { row: 2, col: 4 } },
  },
  {
    id: 'dolphin-and-lantern', order: 20, chapterId: 'legendary-voyages', title: 'Dolphin and Lantern',
    strapline: 'Two very different crews meet.',
    story: 'Combine diagonal routes with diving and jumping moves.',
    objective: 'Either crew: use both helpers to surround the other crew’s leader.',
    lesson: 'Expert coordination', pieceCount: 6, difficulty: 5, available: true,
    vessel: 'sloop', goal: 'corner', gameBalance: 'even', clockWinner: null, noProgressWinner: null, maxMoves: 88, turn: 'boats',
    pieces: { tug: { row: 7, col: 1 }, sloop: { row: 5, col: 3 }, skiff: { row: 6, col: 5 }, whale: { row: 0, col: 6 }, dolphin: { row: 2, col: 4 }, manta: { row: 2, col: 1 } },
  },
  {
    id: 'full-fleet', order: 21, chapterId: 'legendary-voyages', title: 'Full Fleet',
    strapline: 'All 32 travelers fill the bay.',
    story: 'Open routes, coordinate the crew, and protect your leader.',
    objective: 'Either crew: command the full fleet and surround the other crew’s leader.',
    lesson: 'Complete fleet battle', pieceCount: 32, difficulty: 5, available: true,
    vessel: 'cutter', goal: 'corner', gameBalance: 'even', clockWinner: null, noProgressWinner: null, maxMoves: 160, turn: 'boats',
    pieces: {
      shark: { row: 0, col: 0 }, dolphin: { row: 0, col: 1 }, manta: { row: 0, col: 2 }, orca: { row: 0, col: 3 },
      whale: { row: 0, col: 4 }, manta2: { row: 0, col: 5 }, dolphin2: { row: 0, col: 6 }, shark2: { row: 0, col: 7 },
      fish: { row: 1, col: 0 }, fish2: { row: 1, col: 1 }, fish3: { row: 1, col: 2 }, fish4: { row: 1, col: 3 },
      fish5: { row: 1, col: 4 }, fish6: { row: 1, col: 5 }, fish7: { row: 1, col: 6 }, fish8: { row: 1, col: 7 },
      dinghy: { row: 6, col: 0 }, dinghy2: { row: 6, col: 1 }, dinghy3: { row: 6, col: 2 }, dinghy4: { row: 6, col: 3 },
      dinghy5: { row: 6, col: 4 }, dinghy6: { row: 6, col: 5 }, dinghy7: { row: 6, col: 6 }, dinghy8: { row: 6, col: 7 },
      dredger: { row: 7, col: 0 }, skiff: { row: 7, col: 1 }, sloop: { row: 7, col: 2 }, cutter: { row: 7, col: 3 },
      tug: { row: 7, col: 4 }, sloop2: { row: 7, col: 5 }, skiff2: { row: 7, col: 6 }, dredger2: { row: 7, col: 7 },
    },
  },
]

export function voyageById(id) {
  return VOYAGES.find((voyage) => voyage.id === id) || VOYAGES[0]
}

export function chapterFor(voyage) {
  return VOYAGE_CHAPTERS.find((chapter) => chapter.id === voyage.chapterId)
}

export function nextAvailableVoyage(id) {
  const currentIndex = VOYAGES.findIndex((voyage) => voyage.id === id)
  return VOYAGES.slice(currentIndex + 1).find((voyage) => voyage.available) || null
}
